  const allVariants = [
            // Kategori 1: Kritiska doktrinära varianter (12 varianter)
            {category: "critical", verse: "1 Tim 3:16", tr_text: "Gud blev uppenbarad i köttet", un_text: "Han blev uppenbarad i köttet (UN utelämnar: Gud)", impact: "Mest kritisk variant - påverkar inkarnationsläran"},
            {category: "critical", verse: "1 Joh 5:7-8", tr_text: "För tre är de som vittnar i himlen: Fadern, Ordet och den Helige Ande, och dessa tre är ett. Och tre är de som vittnar på jorden", un_text: "Utelämnar hela frasen om himmelska vittnen", impact: "Klaraste trinitariska texten borttagen"},
            {category: "critical", verse: "Joh 1:18", tr_text: "Den enfödde Sonen", un_text: "den enfödde Guden", impact: "Ändrar hur Kristi gudom uttrycks"},
            {category: "critical", verse: "Apg 8:37", tr_text: "Om du tror av hela ditt hjärta, så kan det ske. Och han svarade: Jag tror att Jesus Kristus är Guds Son", un_text: "Hela versen utelämnad", impact: "Trobekännelse före dop borttagen"},
            {category: "critical", verse: "1 Joh 4:3", tr_text: "Jesus Kristus har kommit i köttet", un_text: "Utelämnar \"Kristus har kommit i köttet\"", impact: "Andeprovet försvagat"},
            {category: "critical", verse: "Kol 1:14", tr_text: "förlossningen genom hans blod", un_text: "Utelämnar \"genom hans blod\"", impact: "Blodförsoningen borttagen"},
            {category: "critical", verse: "Matt 18:11", tr_text: "För Människosonen har kommit för att frälsa det som var förlorat", un_text: "Hela versen utelämnad", impact: "Jesu frälsningsuppdrag borttaget"},
            {category: "critical", verse: "Rom 8:1", tr_text: "ingen fördömelse för dem som är i Kristus Jesus, som inte vandrar efter köttet, utan efter Anden", un_text: "Utelämnar \"som inte vandrar efter köttet, utan efter Anden\"", impact: "Etisk kvalifikation borttagen"},
            {category: "critical", verse: "Matt 6:13", tr_text: "för riket är ditt och makten och härligheten i evighet. Amen", un_text: "Utelämnar hela doxologin", impact: "Herrens böns avslutning borttagen"},
            {category: "critical", verse: "Matt 17:21", tr_text: "Men detta slag går inte ut, annat än genom bön och fasta", un_text: "Hela versen utelämnad", impact: "Undervisning om fasta borttagen"},
            {category: "critical", verse: "Mark 9:29", tr_text: "genom bön och fasta", un_text: "Utelämnar \"och fasta\"", impact: "Fasta som andlig disciplin borttagen"},
            {category: "critical", verse: "Mark 16:9-20", tr_text: "Hela avsnittet med uppståndelsescener och missionsbefallingen", un_text: "Inom parentes eller tveksamt", impact: "Uppståndelsen i Markus ifrågasatt"},

            // Kategori 2: Betydande teologiska varianter (13 varianter)
            {category: "significant", verse: "Matt 5:22", tr_text: "vred på sin broder utan giltigt skäl", un_text: "Utelämnar \"utan giltigt skäl\"", impact: "Gör all vrede syndig"},
            {category: "significant", verse: "Matt 5:44", tr_text: "Älska era fiender, välsigna dem som förbannar er, gör väl mot dem som hatar er, och be för dem som hånar er och förföljer er", un_text: "Utelämnar \"välsigna dem som förbannar er, gör väl mot dem som hatar er, hånar er och\"", impact: "Undervisning om fiendekärlek förkortad"},
            {category: "significant", verse: "Matt 9:13", tr_text: "att kalla syndare till omvändelse", un_text: "Utelämnar \"till omvändelse\"", impact: "Omvändelse som syfte borttaget"},
            {category: "significant", verse: "Mark 2:17", tr_text: "utan syndare till omvändelse", un_text: "Utelämnar \"till omvändelse\"", impact: "Samma som ovan"},
            {category: "significant", verse: "Luk 11:2-4", tr_text: "Fader vår, som är i himlarna...Ske din vilja, såsom i himlen, så också på jorden...utan fräls oss från det onda", un_text: "Utelämnar flera delar", impact: "Stora skillnader i Herrens bön"},
            {category: "significant", verse: "Matt 6:4, 6, 18", tr_text: "ska belöna dig synligt", un_text: "Utelämnar \"synligt\" (tre gånger)", impact: "Belöningens karaktär ändrad"},
            {category: "significant", verse: "1 Kor 7:5", tr_text: "fastan och bönen", un_text: "Utelämnar \"fastan och\"", impact: "Fasta borttagen från äktenskapsråd"},
            {category: "significant", verse: "Matt 23:14", tr_text: "Ve er, skriftlärda och fariseer, ni hycklare, för ni plundrar änkors hus", un_text: "Hela versen utelämnad", impact: "Ett av sju ve-rop borttaget"},
            {category: "significant", verse: "Luk 4:4", tr_text: "utan av varje ord som kommer från Gud", un_text: "Utelämnar \"av varje ord från Gud\"", impact: "Skriftens tillräcklighet försvagad"},
            {category: "significant", verse: "Luk 9:55-56", tr_text: "Ni vet inte av vilken ande ni är. För Människosonen har inte kommit för att förgöra människoliv, utan för att frälsa dem", un_text: "Betydligt förkortad eller utelämnad", impact: "Jesu mission att frälsa borttagen"},
            {category: "significant", verse: "Joh 5:3-4", tr_text: "Beskrivning av ängeln som rörde vattnet och helade", un_text: "Vers 4 helt utelämnad", impact: "Förklaringen till Betesda-dammen borta"},
            {category: "significant", verse: "Matt 27:35", tr_text: "att det skulle uppfyllas som var sagt genom profeten: De har delat mina kläder mellan sig", un_text: "Hela uppfyllelse-formeln utelämnad", impact: "Profetie-koppling borttagen"},
            {category: "significant", verse: "Luk 23:17", tr_text: "För vid högtiden måste han frige en fånge åt dem", un_text: "Hela versen utelämnad", impact: "Förklaring till Barabbas borttagen"},

            // Kategori 3: Referenser till Jesus namn och titlar (33 varianter)
            {category: "jesus", verse: "Matt 1:25", tr_text: "sin Son, den förstfödde", un_text: "en son (utelämnar: den förstfödde)", impact: "Marias andra barn ej antydda"},
            {category: "jesus", verse: "Matt 4:12", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 4:18", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 4:23", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 8:3", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 8:5", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 8:7", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 8:29", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 9:12", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 12:25", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 13:36", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 13:51", tr_text: "Jesus", un_text: "utelämnar", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 14:14", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 14:22", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 15:16", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 15:30", tr_text: "Jesus", un_text: "hans", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 16:20", tr_text: "att han var Jesus Kristus", un_text: "Utelämnar \"Jesus\"", impact: "Mindre komplett titel"},
            {category: "jesus", verse: "Matt 17:20", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 18:2", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Matt 20:22", tr_text: "Dopet med Kristi dop", un_text: "Utelämnar frågan om dopet", impact: "Symbolik borttagen"},
            {category: "jesus", verse: "Matt 20:23", tr_text: "Dopet med Kristi dop", un_text: "Utelämnar svaret om dopet", impact: "Symbolik borttagen"},
            {category: "jesus", verse: "Mark 1:41", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Mark 5:19", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Mark 6:34", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Mark 7:27", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Mark 8:1", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Luk 5:34", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Luk 9:43", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Luk 9:60", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Luk 10:41", tr_text: "Jesus", un_text: "Herren", impact: "Olika titel"},
            {category: "jesus", verse: "Luk 22:63", tr_text: "Jesus", un_text: "honom", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Joh 6:14", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "jesus", verse: "Upp 1:9", tr_text: "Jesu Kristi", un_text: "Utelämnar \"Kristi\"", impact: "Mindre komplett titel"},

            // Kategori 4: Guds namn och attribut (10 varianter)
            {category: "god", verse: "Matt 6:33", tr_text: "Guds rike", un_text: "Sätter \"Guds\" inom parentes", impact: "Osäkerhet om \"Guds\""},
            {category: "god", verse: "Matt 21:12", tr_text: "Guds tempel", un_text: "Utelämnar \"Guds\"", impact: "Mindre specifikt"},
            {category: "god", verse: "Matt 22:30", tr_text: "Guds änglar", un_text: "Utelämnar \"Guds\"", impact: "Mindre specifikt"},
            {category: "god", verse: "Matt 23:8", tr_text: "er Läromästare, Kristus", un_text: "Utelämnar \"Kristus\"", impact: "Läromästaren ej identifierad"},
            {category: "god", verse: "Rom 14:10", tr_text: "Kristi domstol", un_text: "Guds domstol", impact: "Domare ändrad"},
            {category: "god", verse: "1 Tim 1:17", tr_text: "den ende vise Guden", un_text: "Utelämnar \"vise\"", impact: "Attribut borttaget"},
            {category: "god", verse: "1 Tim 2:7", tr_text: "jag talar sanning i Kristus", un_text: "Utelämnar \"i Kristus\"", impact: "Auktoritet försvagad"},
            {category: "god", verse: "Upp 1:8", tr_text: "Herren", un_text: "Herren Gud", impact: "Ändring av titel"},
            {category: "god", verse: "Upp 11:17", tr_text: "du som är och som var och som ska komma", un_text: "Utelämnar \"och som ska komma\"", impact: "Evighetsaspekt borttagen"},
            {category: "god", verse: "Upp 14:1", tr_text: "hans Faders namn", un_text: "hans namn och hans Faders namn", impact: "Namn fördubblat"},

            // Kategori 5: Den Helige Ande (7 varianter)
            {category: "spirit", verse: "Apg 8:18", tr_text: "den Helige Ande gavs", un_text: "Utelämnar \"Helige\"", impact: "Mindre specifikt"},
            {category: "spirit", verse: "1 Kor 2:13", tr_text: "som den Helige Ande lär", un_text: "Utelämnar \"Helige\"", impact: "Mindre specifikt"},
            {category: "spirit", verse: "Apg 6:3", tr_text: "uppfyllda av den Helige Ande", un_text: "Utelämnar \"Helige\"", impact: "Mindre specifikt"},
            {category: "spirit", verse: "Ef 5:9", tr_text: "Andens frukt", un_text: "ljusets frukt", impact: "Helt annorlunda betydelse"},
            {category: "spirit", verse: "Luk 10:21", tr_text: "Jesus fröjdade sig i anden", un_text: "han i den helige Ande", impact: "Mer specifikt i UN"},
            {category: "spirit", verse: "Luk 1:28", tr_text: "välsignad är du bland kvinnor", un_text: "Utelämnar \"välsignad är du bland kvinnor\"", impact: "Marias välsignelse borttagen"},
            {category: "spirit", verse: "1 Petr 1:22", tr_text: "renat era själar genom Anden", un_text: "Utelämnar \"genom Anden\"", impact: "Andens roll borttagen"},

            // Kategori 6: Jungfrufödelsen och familj (5 varianter)
            {category: "family", verse: "Matt 1:25", tr_text: "sin Son, den förstfödde", un_text: "en son", impact: "Fråga om Marias andra barn"},
            {category: "family", verse: "Luk 2:33", tr_text: "Josef och hans mor", un_text: "Hans far och mor", impact: "Josef kallad far"},
            {category: "family", verse: "Luk 2:43", tr_text: "Josef och hans mor", un_text: "hans föräldrar", impact: "Josef kallad förälder"},
            {category: "family", verse: "Matt 13:55", tr_text: "Jakob och Joses", un_text: "Jakob och Josef", impact: "Namnvariant"},
            {category: "family", verse: "Matt 27:56", tr_text: "Jakobs och Joses mor", un_text: "Jakobs och Josefs mor", impact: "Namnvariant"},

            // Kategori 7: Undergörelser (8 varianter)
            {category: "miracles", verse: "Matt 8:15", tr_text: "tjänade dem", un_text: "tjänade honom", impact: "Vem som tjänades ändrat"},
            {category: "miracles", verse: "Matt 12:22", tr_text: "den blinde och stumme", un_text: "Utelämnar \"blinde och\"", impact: "Mindre mirakel"},
            {category: "miracles", verse: "Matt 14:24", tr_text: "mitt på sjön", un_text: "många stadier från land", impact: "Annorlunda beskrivning"},
            {category: "miracles", verse: "Matt 20:16", tr_text: "För många är kallade men få är utvalda", un_text: "Utelämnar hela frasen", impact: "Viktig princip borttagen"},
            {category: "miracles", verse: "Matt 20:22-23", tr_text: "Frågor om att dricka bägaren och döpas med Jesu dop", un_text: "Utelämnar dopfrågan och svaret", impact: "Symbolik borttagen"},
            {category: "miracles", verse: "Mark 1:42", tr_text: "när han hade sagt det", un_text: "Utelämnar \"när han hade sagt det\"", impact: "Detalj borttagen"},
            {category: "miracles", verse: "Mark 3:5", tr_text: "frisk som den andra", un_text: "Utelämnar \"som den andra\"", impact: "Mindre komplett"},
            {category: "miracles", verse: "Mark 6:11", tr_text: "Hela versen med domen över Sodom och Gomorra", un_text: "Utelämnar resten av versen", impact: "Domsuttalande borttaget"},

            // Kategori 8: Etik och kristet liv (9 varianter)
            {category: "ethics", verse: "Matt 5:27", tr_text: "till dem i forna tider", un_text: "Utelämnar \"till dem i forna tider\"", impact: "Mindre specifikt"},
            {category: "ethics", verse: "Matt 5:47", tr_text: "tullindrivarna", un_text: "hedningarna", impact: "Annorlunda grupp"},
            {category: "ethics", verse: "Matt 6:1", tr_text: "er gåva", un_text: "era goda gärningar", impact: "Annorlunda fokus"},
            {category: "ethics", verse: "Matt 6:12", tr_text: "förlåter", un_text: "har förlåtit", impact: "Tidsskillnad"},
            {category: "ethics", verse: "Rom 1:29", tr_text: "orättfärdighet, otukt, ondska", un_text: "Utelämnar \"otukt\"", impact: "Synd borttagen"},
            {category: "ethics", verse: "Rom 1:31", tr_text: "oförsonliga, obarmhärtiga", un_text: "Utelämnar \"oförsonliga\"", impact: "Synd borttagen"},
            {category: "ethics", verse: "Jak 4:4", tr_text: "Ni äktenskapsbrytare och äktenskapsbryterskor", un_text: "Utelämnar \"äktenskapsbrytare och\"", impact: "Mindre skarpt"},
            {category: "ethics", verse: "1 Petr 3:8", tr_text: "barmhärtiga och vänliga", un_text: "ödmjuka", impact: "Annorlunda dygd"},
            {category: "ethics", verse: "1 Petr 4:1", tr_text: "Kristus har lidit i köttet för oss", un_text: "Utelämnar \"för oss\"", impact: "Försoningsteologi påverkad"},

            // Kategori 9: Geografiska och personnamn (15 varianter)
            {category: "names", verse: "Matt 8:28", tr_text: "gergesenernas", un_text: "gadarenernas", impact: "Olika plats"},
            {category: "names", verse: "Matt 15:39", tr_text: "Magdalas", un_text: "Magadans", impact: "Olika plats"},
            {category: "names", verse: "Mark 1:2", tr_text: "hos profeterna", un_text: "profeten Jesaja", impact: "Mer specifikt"},
            {category: "names", verse: "Mark 5:1", tr_text: "gadarenernas", un_text: "gerasenernas", impact: "Olika plats"},
            {category: "names", verse: "Mark 8:26", tr_text: "Hela avslutningsfrasen", un_text: "Utelämnar resten av versen", impact: "Instruktion borttagen"},
            {category: "names", verse: "Luk 3:26", tr_text: "Namnform i släkttavlan", un_text: "Olika stavning", impact: "Genealogisk skillnad"},
            {category: "names", verse: "Luk 3:28", tr_text: "Namnform i släkttavlan", un_text: "Olika stavning", impact: "Genealogisk skillnad"},
            {category: "names", verse: "Luk 3:29", tr_text: "Namnform i släkttavlan", un_text: "Olika stavning", impact: "Genealogisk skillnad"},
            {category: "names", verse: "Luk 3:31", tr_text: "Namnform i släkttavlan", un_text: "Olika stavning", impact: "Genealogisk skillnad"},
            {category: "names", verse: "Luk 3:32", tr_text: "Namnform i släkttavlan", un_text: "Olika stavning", impact: "Genealogisk skillnad"},
            {category: "names", verse: "Luk 3:33", tr_text: "Namnform i släkttavlan", un_text: "Olika stavning", impact: "Genealogisk skillnad"},
            {category: "names", verse: "Luk 4:44", tr_text: "Galileen", un_text: "Judeen", impact: "Annorlunda område"},
            {category: "names", verse: "Apg 18:7", tr_text: "Justus", un_text: "Titius Justus", impact: "Mer komplett namn"},
            {category: "names", verse: "Apg 27:14", tr_text: "Euroklydon", un_text: "Eurakylon", impact: "Namnvariant"},
            {category: "names", verse: "Apg 27:16", tr_text: "Klauda", un_text: "Kauda", impact: "Namnvariant"},

            // Kategori 10: Församlingsordning och sakrament (8 varianter)
            {category: "church", verse: "1 Kor 11:24", tr_text: "Tag, ät. Detta är min kropp som är bruten för er", un_text: "Utelämnar \"Tag, ät\" och \"bruten\"", impact: "Nattvardsinstruktion förkortad"},
            {category: "church", verse: "1 Kor 11:29", tr_text: "äter och dricker på ett ovärdigt sätt...Herrens kropp", un_text: "Utelämnar \"på ett ovärdigt sätt\" och \"Herrens\"", impact: "Kvalifikation borttagen"},
            {category: "church", verse: "Matt 28:19", tr_text: "döpa dem i Faderns och Sonens och den helige Andes namn", un_text: "Samma text", impact: "Text kvarstår men vissa ifrågasätter"},
            {category: "church", verse: "Apg 2:41", tr_text: "De som då med glädje tog emot hans ord", un_text: "Utelämnar \"med glädje\"", impact: "Emotionell aspekt borttagen"},
            {category: "church", verse: "Apg 2:47", tr_text: "till församlingen", un_text: "Utelämnar \"till församlingen\"", impact: "Mindre specifikt"},
            {category: "church", verse: "Apg 8:16", tr_text: "döpas i Herrens Jesu namn", un_text: "Jesu Kristi namn", impact: "Fullständigare titel i UN"},
            {category: "church", verse: "Apg 10:48", tr_text: "döpas i Herrens namn", un_text: "Jesu Kristi namn", impact: "Mer specifikt i UN"},
            {category: "church", verse: "Apg 19:5", tr_text: "Herrens Jesu namn", un_text: "Utelämnar \"Jesu\"", impact: "Mindre specifikt"},

            // Kategori 11: Uppståndelsen och efteråt (8 varianter)
            {category: "resurrection", verse: "Mark 16:9-20", tr_text: "Hela avsnittet med uppståndelsen, missionsbefallingen, tecken", un_text: "Inom dubbla parenteser", impact: "Hela slutet ifrågasatt"},
            {category: "resurrection", verse: "Luk 24:6", tr_text: "Han är inte här utan har uppstått", un_text: "Viss osäkerhet", impact: "Uppståndelseförkunnelse osäker"},
            {category: "resurrection", verse: "Luk 24:12", tr_text: "Petrus besök vid graven", un_text: "Vissa handskrifter utelämnar", impact: "Petrus vittnesbörd borttaget"},
            {category: "resurrection", verse: "Luk 24:40", tr_text: "Han visade dem sina händer och sina fötter", un_text: "Vissa ifrågasätter", impact: "Bevis för uppståndelsen borttaget"},
            {category: "resurrection", verse: "Luk 24:51", tr_text: "och blev upptagen till himlen", un_text: "Vissa handskrifter ifrågasätter", impact: "Himmelfärden osäker"},
            {category: "resurrection", verse: "Matt 28:6", tr_text: "där Herren låg", un_text: "han", impact: "Mindre specifikt"},
            {category: "resurrection", verse: "Matt 28:9", tr_text: "när de var på väg för att berätta det för hans lärjungar", un_text: "Utelämnar hela frasen", impact: "Kontext borttagen"},
            {category: "resurrection", verse: "Joh 20:17", tr_text: "min Fader", un_text: "Utelämnar \"min\"", impact: "Mindre personligt"},

            // Kategori 12: Profetior och uppfyllelser (5 varianter)
            {category: "prophecy", verse: "Matt 27:35", tr_text: "att det skulle uppfyllas som var sagt genom profeten: De har delat mina kläder mellan sig", un_text: "Utelämnar resten av versen", impact: "Profeti-koppling borttagen"},
            {category: "prophecy", verse: "Matt 21:4", tr_text: "Men allt detta hände för att det skulle uppfyllas", un_text: "Utelämnar \"allt\"", impact: "Mindre emfatiskt"},
            {category: "prophecy", verse: "Mark 13:14", tr_text: "som profeten Daniel har talat om", un_text: "Utelämnar \"som profeten Daniel har talat om\"", impact: "Profet-hänvisning borttagen"},
            {category: "prophecy", verse: "Luk 1:78", tr_text: "soluppgången från höjden har besökt oss", un_text: "ska besöka oss", impact: "Tid ändrad"},
            {category: "prophecy", verse: "Joh 2:17", tr_text: "Nitälskan för ditt hus har förtärt mig", un_text: "ska förtära", impact: "Tid ändrad"},

            // Kategori 13: Doktrin om synd och helgelse (7 varianter)
            {category: "sin", verse: "Rom 13:9", tr_text: "du skall inte bära falskt vittnesbörd", un_text: "Utelämnar \"du ska inte bära falskt vittnesbörd\"", impact: "Ett bud borttaget"},
            {category: "sin", verse: "Gal 5:19", tr_text: "hor, otukt, orenhet", un_text: "Utelämnar \"hor\"", impact: "Synd borttagen"},
            {category: "sin", verse: "Gal 5:21", tr_text: "missunnsamhet, mord, fylleri", un_text: "Utelämnar \"mord\"", impact: "Synd borttagen"},
            {category: "sin", verse: "Kol 2:11", tr_text: "köttets syndakropp", un_text: "kropp", impact: "Syndens betoning borttagen"},
            {category: "sin", verse: "Kol 3:6", tr_text: "över olydnadens barn", un_text: "Tveksam, sätts inom parentes", impact: "Osäkerhet om domsuttalande"},
            {category: "sin", verse: "1 Petr 4:3", tr_text: "vi under den förflutna tiden av vårt liv", un_text: "Utelämnar \"vi\" och \"liv\"", impact: "Mindre personligt"},
            {category: "sin", verse: "2 Petr 2:2", tr_text: "deras fördärv", un_text: "utsvävningar", impact: "Annorlunda synd"},

            // Kategori 14: Kristen kallelse och tjänst (7 varianter)
            {category: "ministry", verse: "Matt 10:3", tr_text: "Lebbeus som kallades Taddeus", un_text: "Utelämnar \"Lebbeus som kallades\"", impact: "Namn förenklat"},
            {category: "ministry", verse: "Mark 3:14", tr_text: "tolv", un_text: "Tillägger inom parentes \"(som han kallade apostlar)\"", impact: "UN mer specifik"},
            {category: "ministry", verse: "Mark 3:16", tr_text: "Och Simon gav han namnet Petrus", un_text: "Tillägger \"Han utsåg dessa tolv\"", impact: "UN tydligare"},
            {category: "ministry", verse: "Apg 1:8", tr_text: "ska vara vittnen åt mig", un_text: "mina vittnen", impact: "Olika formulering"},
            {category: "ministry", verse: "Rom 15:19", tr_text: "genom Guds Andes kraft", un_text: "Utelämnar \"Guds\"", impact: "Mindre specifikt"},
            {category: "ministry", verse: "2 Kor 4:10", tr_text: "Herren Jesu död", un_text: "Utelämnar \"Herren\"", impact: "Mindre specifikt"},
            {category: "ministry", verse: "Ef 4:9", tr_text: "först och delarna", un_text: "Utelämnar \"först\", tveksam om \"delarna\"", impact: "Mindre tydligt"},

            // Kategori 15: Himmelska scener och eskatologi (20 varianter)
            {category: "eschatology", verse: "Upp 1:8", tr_text: "begynnelsen och änden", un_text: "Utelämnar \"begynnelsen och änden\"", impact: "Titel borttagen"},
            {category: "eschatology", verse: "Upp 1:11", tr_text: "Jag är Alfa och Omega, den förste och den siste. Och vad du ser, skriv ner det i en bokrulle, och sänd den till de sju församlingarna, som är i Asien", un_text: "Utelämnar \"Jag är Alfa och Omega, den förste och den siste\", \"som är i Asien\"", impact: "Kristus titel och geografisk specificering borttagen"},
            {category: "eschatology", verse: "Upp 2:13", tr_text: "dina gärningar och", un_text: "Utelämnar \"dina gärningar och\"", impact: "Mindre komplett"},
            {category: "eschatology", verse: "Upp 2:15", tr_text: "vilken jag hatar", un_text: "på samma sätt", impact: "Annorlunda formulering"},
            {category: "eschatology", verse: "Upp 5:9", tr_text: "oss åt Gud", un_text: "människor", impact: "Annorlunda objekt"},
            {category: "eschatology", verse: "Upp 5:10", tr_text: "oss till kungar och vi ska regera", un_text: "dem till ett kungadöme och de ska", impact: "Annorlunda person"},
            {category: "eschatology", verse: "Upp 6:1", tr_text: "Kom och se", un_text: "Utelämnar \"och se\"", impact: "Uppmaningen förkortad"},
            {category: "eschatology", verse: "Upp 6:3", tr_text: "Kom och se", un_text: "Utelämnar \"och se\"", impact: "Uppmaningen förkortad"},
            {category: "eschatology", verse: "Upp 6:5", tr_text: "Kom och se", un_text: "Utelämnar \"och se\"", impact: "Uppmaningen förkortad"},
            {category: "eschatology", verse: "Upp 6:7", tr_text: "Kom och se", un_text: "Utelämnar \"och se\"", impact: "Uppmaningen förkortad"},
            {category: "eschatology", verse: "Upp 8:7", tr_text: "Text om hagelstorm", un_text: "Tillägger \"och en tredjedel av jorden brändes upp\"", impact: "UN mer detaljerad"},
            {category: "eschatology", verse: "Upp 11:15", tr_text: "riken", un_text: "rike", impact: "Singular istället för plural"},
            {category: "eschatology", verse: "Upp 14:5", tr_text: "inför Guds tron", un_text: "Utelämnar \"inför Guds tron\"", impact: "Mindre specifikt"},
            {category: "eschatology", verse: "Upp 15:3", tr_text: "de heligas konung", un_text: "folkens", impact: "Annorlunda herravälde"},
            {category: "eschatology", verse: "Upp 19:1", tr_text: "priset och Herren", un_text: "Utelämnar båda", impact: "Doxologi förkortad"},
            {category: "eschatology", verse: "Upp 20:9", tr_text: "från Gud", un_text: "Utelämnar \"från Gud\"", impact: "Källan borttagen"},
            {category: "eschatology", verse: "Upp 20:12", tr_text: "inför Gud", un_text: "tronen", impact: "Annorlunda objekt"},
            {category: "eschatology", verse: "Upp 21:24", tr_text: "som blivit frälsta och ära", un_text: "Utelämnar båda", impact: "Kvalifikation borttagen"},
            {category: "eschatology", verse: "Upp 22:14", tr_text: "Saliga är de som håller hans bud", un_text: "Saliga är de som tvättar sina kläder", impact: "Helt annorlunda villkor"},
            {category: "eschatology", verse: "Upp 22:21", tr_text: "Vår, Kristi, er, Amen", un_text: "Utelämnar allt utom \"med de heliga\"", impact: "Avslutning förkortad"},

            // Kategori 16: Mindre varianter med viss teologisk betydelse (82 varianter)
            {category: "minor", verse: "Matt 6:4", tr_text: "synligt", un_text: "Utelämnar", impact: "Belöningens art ändrad"},
            {category: "minor", verse: "Matt 6:6", tr_text: "synligt", un_text: "Utelämnar", impact: "Belöningens art ändrad"},
            {category: "minor", verse: "Matt 6:18", tr_text: "synligt", un_text: "Utelämnar", impact: "Belöningens art ändrad"},
            {category: "minor", verse: "Matt 19:9", tr_text: "och den som gifter sig med den frånskilda kvinnan begår äktenskapsbrott", un_text: "Utelämnar hela frasen", impact: "Undervisning om omgifte borttagen"},
            {category: "minor", verse: "Matt 19:16", tr_text: "Gode mästare", un_text: "Utelämnar \"Gode\"", impact: "Tilltal ändrat"},
            {category: "minor", verse: "Matt 19:17", tr_text: "Varför kallar du mig god? Ingen är god utom en, det är Gud", un_text: "Varför frågar du mig om vad som är gott? Det finns bara en som är god", impact: "Helt annorlunda svar"},
            {category: "minor", verse: "Matt 19:20", tr_text: "från min ungdom", un_text: "Utelämnar \"från min ungdom\"", impact: "Tidsaspekt borttagen"},
            {category: "minor", verse: "Matt 19:29", tr_text: "eller hustru", un_text: "Utelämnar \"eller hustru\"", impact: "En relation borttagen"},
            {category: "minor", verse: "Matt 24:36", tr_text: "inte ens himlens änglar och min", un_text: "Tillägger \"inte ens Sonen\", utelämnar \"min\"", impact: "Jesu kunskap begränsad i UN"},
            {category: "minor", verse: "Matt 24:42", tr_text: "stund", un_text: "dag", impact: "Annorlunda tidsenhet"},
            {category: "minor", verse: "Matt 24:48", tr_text: "att komma", un_text: "Utelämnar \"att komma\"", impact: "Mindre specifikt"},
            {category: "minor", verse: "Mark 1:1", tr_text: "Guds Son", un_text: "Vissa handskrifter ifrågasätter", impact: "Titel osäker"},
            {category: "minor", verse: "Mark 1:2", tr_text: "hos profeterna", un_text: "profeten Jesaja", impact: "Mer specifikt"},
            {category: "minor", verse: "Mark 1:8", tr_text: "i sanning", un_text: "Utelämnar \"i sanning\"", impact: "Mindre emfatiskt"},
            {category: "minor", verse: "Mark 1:31", tr_text: "Och genast", un_text: "Utelämnar \"Genast\"", impact: "Tidsaspekt borttagen"},
            {category: "minor", verse: "Mark 2:2", tr_text: "Då samlades genast", un_text: "Utelämnar \"genast\"", impact: "Tidsaspekt borttagen"},
            {category: "minor", verse: "Mark 2:16", tr_text: "de skriftlärda och fariseerna", un_text: "de skriftlärda bland fariseerna", impact: "Annorlunda gruppering"},
            {category: "minor", verse: "Mark 2:22", tr_text: "det nya vinet", un_text: "Utelämnar \"nya\"", impact: "Mindre specifikt"},
            {category: "minor", verse: "Mark 6:16", tr_text: "från de döda", un_text: "Utelämnar \"från de döda\"", impact: "Mindre specifikt"},
            {category: "minor", verse: "Mark 6:20", tr_text: "rättade sig mycket efter honom", un_text: "blev han många gånger villrådig", impact: "Helt annorlunda reaktion"},
            {category: "minor", verse: "Mark 6:33", tr_text: "och samlades till honom", un_text: "Utelämnar \"och samlades till honom\"", impact: "Handling borttagen"},
            {category: "minor", verse: "Mark 7:8", tr_text: "Hela versen om kannor och bägare", un_text: "Utelämnar resten av versen", impact: "Exempel borttagna"},
            {category: "minor", verse: "Mark 7:16", tr_text: "Den som har öron till att höra, han må höra", un_text: "Hela versen utelämnad", impact: "Uppmaning borttagen"},
            {category: "minor", verse: "Mark 9:42", tr_text: "som tror på mig", un_text: "Tveksam, sätts inom parentes", impact: "Osäkerhet om trons objekt"},
            {category: "minor", verse: "Mark 9:44", tr_text: "där deras mask inte dör och elden inte släcks", un_text: "Hela versen utelämnad", impact: "Helvetesbeskrivning borttagen"},
            {category: "minor", verse: "Mark 9:46", tr_text: "där deras mask inte dör och elden inte släcks", un_text: "Hela versen utelämnad", impact: "Helvetesbeskrivning borttagen"},
            {category: "minor", verse: "Mark 9:49", tr_text: "och varje offer måste saltas med salt", un_text: "Utelämnar hela frasen", impact: "Offer-jämförelse borttagen"},
            {category: "minor", verse: "Mark 10:24", tr_text: "för dem som förtröstar på rikedomar", un_text: "Utelämnar hela frasen", impact: "Kvalifikation borttagen"},
            {category: "minor", verse: "Mark 10:29", tr_text: "eller hustru", un_text: "Utelämnar \"eller hustru\"", impact: "En relation borttagen"},
            {category: "minor", verse: "Mark 11:10", tr_text: "i Herrens namn", un_text: "Utelämnar \"i Herrens namn\"", impact: "Kvalifikation borttagen"},
            {category: "minor", verse: "Mark 11:26", tr_text: "Hela versen om förlåtelse", un_text: "Hela versen utelämnad", impact: "Undervisning om förlåtelse borttagen"},
            {category: "minor", verse: "Mark 13:33", tr_text: "och be", un_text: "Utelämnar \"och be\"", impact: "Bön borttagen"},
            {category: "minor", verse: "Mark 14:19", tr_text: "Och en annan: Inte är det väl jag?", un_text: "Utelämnar denna upprepning", impact: "Upprepning borttagen"},
            {category: "minor", verse: "Mark 14:24", tr_text: "det nya förbundet", un_text: "Utelämnar \"nya\"", impact: "Mindre specifikt"},
            {category: "minor", verse: "Mark 14:27", tr_text: "I denna natt, för min skull", un_text: "Utelämnar båda", impact: "Tid och orsak borttagna"},
            {category: "minor", verse: "Mark 14:68", tr_text: "Och tuppen gol", un_text: "Tveksam, sätts inom parentes", impact: "Händelse osäker"},
            {category: "minor", verse: "Mark 14:70", tr_text: "och din dialekt låter så", un_text: "Utelämnar denna detalj", impact: "Bevis borttaget"},
            {category: "minor", verse: "Mark 15:28", tr_text: "Och bland lagöverträdare blev han räknad", un_text: "Hela versen utelämnad", impact: "Profeti-uppfyllelse borttagen"},
            {category: "minor", verse: "Mark 15:39", tr_text: "med ett sådant rop", un_text: "på ett sådant sätt", impact: "Annorlunda beskrivning"},
            {category: "minor", verse: "Mark 16:8", tr_text: "hastigt", un_text: "Utelämnar \"hastigt\"", impact: "Tidsaspekt borttagen"},
            {category: "minor", verse: "Luk 1:28", tr_text: "välsignad är du bland kvinnor", un_text: "Utelämnar hela frasen", impact: "Marias välsignelse borttagen"},
            {category: "minor", verse: "Luk 1:29", tr_text: "då hon såg honom", un_text: "Utelämnar denna detalj", impact: "Händelse förenklad"},
            {category: "minor", verse: "Luk 2:5", tr_text: "hustru", un_text: "Utelämnar \"hustru\"", impact: "Status ändrad"},
            {category: "minor", verse: "Luk 2:17", tr_text: "vida omkring", un_text: "Utelämnar \"vida omkring\"", impact: "Räckvidd begränsad"},
            {category: "minor", verse: "Luk 2:22", tr_text: "hennes", un_text: "deras", impact: "Annorlunda person"},
            {category: "minor", verse: "Luk 2:38", tr_text: "Herren", un_text: "Gud", impact: "Annorlunda objekt"},
            {category: "minor", verse: "Luk 2:40", tr_text: "i anden", un_text: "Utelämnar \"i anden\"", impact: "Andlig aspekt borttagen"},
            {category: "minor", verse: "Luk 2:42", tr_text: "till Jerusalem", un_text: "Utelämnar \"till Jerusalem\"", impact: "Destination borttagen"},
            {category: "minor", verse: "Luk 4:8", tr_text: "Gå bort ifrån mig Satan, för", un_text: "Utelämnar \"Gå bort ifrån mig Satan, för\"", impact: "Befallning borttagen"},
            {category: "minor", verse: "Luk 4:18", tr_text: "till att hela dem som har förkrossade hjärtan", un_text: "Utelämnar hela frasen", impact: "En uppgift borttagen"},
            {category: "minor", verse: "Luk 4:41", tr_text: "Kristus", un_text: "Utelämnar \"Kristus\"", impact: "Titel borttagen"},
            {category: "minor", verse: "Luk 5:15", tr_text: "av honom", un_text: "Utelämnar \"av honom\"", impact: "Agent borttagen"},
            {category: "minor", verse: "Luk 5:33", tr_text: "Varför", un_text: "Utelämnar \"Varför\"", impact: "Fråga förkortad"},
            {category: "minor", verse: "Luk 6:1", tr_text: "näst efter den första", un_text: "Utelämnar hela frasen", impact: "Tidsbestämning borttagen"},
            {category: "minor", verse: "Luk 6:5", tr_text: "också", un_text: "Utelämnar \"också\"", impact: "Emfas borttagen"},
            {category: "minor", verse: "Luk 6:10", tr_text: "som den andra", un_text: "Utelämnar \"som den andra\"", impact: "Jämförelse borttagen"},
            {category: "minor", verse: "Luk 6:48", tr_text: "eftersom det var grundat på klippan", un_text: "var väl byggt", impact: "Annorlunda förklaring"},
            {category: "minor", verse: "Luk 7:11", tr_text: "många", un_text: "Utelämnar \"många\"", impact: "Mängd ospecificerad"},
            {category: "minor", verse: "Luk 7:19", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "minor", verse: "Luk 7:22", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "minor", verse: "Luk 7:28", tr_text: "För, profet, Döparen", un_text: "Utelämnar alla tre", impact: "Mindre emfatiskt"},
            {category: "minor", verse: "Luk 7:31", tr_text: "Och Herren sa", un_text: "Utelämnar hela inledningen", impact: "Talare mindre tydlig"},
            {category: "minor", verse: "Luk 8:3", tr_text: "honom", un_text: "dem", impact: "Annorlunda objekt"},
            {category: "minor", verse: "Luk 8:27", tr_text: "sedan en ganska lång tid", un_text: "hade inte på länge haft några kläder på sig", impact: "Annorlunda formulering"},
            {category: "minor", verse: "Luk 8:43", tr_text: "och som hade gjort av med allt hon ägde på läkare", un_text: "Tveksam, sätts inom parentes", impact: "Osäkerhet om denna detalj"},
            {category: "minor", verse: "Luk 9:7", tr_text: "av honom", un_text: "Utelämnar \"av honom\"", impact: "Agent borttagen"},
            {category: "minor", verse: "Luk 9:35", tr_text: "älskade", un_text: "utvalde", impact: "Annorlunda relation"},
            {category: "minor", verse: "Luk 10:11", tr_text: "oss", un_text: "våra fötter", impact: "Mindre personligt"},
            {category: "minor", verse: "Luk 10:15", tr_text: "ska väl du upphöjas till himlen?", un_text: "Annorlunda formulering", impact: "Retorisk fråga i UN"},
            {category: "minor", verse: "Luk 10:20", tr_text: "hellre", un_text: "Utelämnar \"hellre\"", impact: "Jämförelse borttagen"},
            {category: "minor", verse: "Luk 10:39", tr_text: "Jesu", un_text: "Herrens", impact: "Annorlunda titel"},
            {category: "minor", verse: "Luk 12:31", tr_text: "Guds rike och allt", un_text: "hans rike, utelämnar \"allt\"", impact: "Mindre specifikt"},
            {category: "minor", verse: "Luk 13:2", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "minor", verse: "Luk 13:35", tr_text: "öde, sannerligen", un_text: "Utelämnar båda", impact: "Mindre emfatiskt"},
            {category: "minor", verse: "Luk 14:3", tr_text: "Frågan om det är tillåtet", un_text: "Tillägger \"eller inte?\"", impact: "UN mer direkt"},
            {category: "minor", verse: "Luk 14:5", tr_text: "åsna", un_text: "son", impact: "Helt annorlunda objekt"},
            {category: "minor", verse: "Luk 16:9", tr_text: "när ni slutar", un_text: "när det tar slut", impact: "Annorlunda subjekt"},
            {category: "minor", verse: "Luk 17:3", tr_text: "mot dig", un_text: "Utelämnar \"mot dig\"", impact: "Mindre personligt"},
            {category: "minor", verse: "Luk 17:4", tr_text: "om dagen", un_text: "Utelämnar \"om dagen\"", impact: "Tidsaspekt borttagen"},
            {category: "minor", verse: "Luk 17:9", tr_text: "Nej, menar jag", un_text: "Utelämnar hela svaret", impact: "Svar borttaget"},
            {category: "minor", verse: "Luk 17:24", tr_text: "också", un_text: "Utelämnar \"också\"", impact: "Jämförelse försvagad"},
            {category: "minor", verse: "Luk 17:33", tr_text: "rädda", un_text: "vinna", impact: "Annorlunda verb"},
            {category: "minor", verse: "Luk 17:36", tr_text: "Två ska vara ute på marken...", un_text: "Hela versen utelämnad", impact: "Exempel borttaget"},
            {category: "minor", verse: "Luk 22:43-44", tr_text: "Hela beskrivningen av ängeln och blodssvetten", un_text: "Tveksam, sätts inom dubbla parenteser", impact: "Lidandet ifrågasatt"},
            {category: "minor", verse: "Luk 23:17", tr_text: "För vid högtiden måste han frige en fånge åt dem", un_text: "Hela versen utelämnad", impact: "Förklaring till Barabbas borttagen"},

            // Kategori 17: Johannesevangeliet specifika varianter (73 varianter)
            {category: "john", verse: "Joh 1:27", tr_text: "är den och som är förmer än mig", un_text: "Utelämnar båda", impact: "Mindre emfatiskt"},
            {category: "john", verse: "Joh 1:28", tr_text: "Betabara", un_text: "Betania", impact: "Annorlunda plats"},
            {category: "john", verse: "Joh 1:42", tr_text: "Jonas", un_text: "Johannes", impact: "Annorlunda faders namn"},
            {category: "john", verse: "Joh 1:51", tr_text: "Härefter", un_text: "Utelämnar \"Härefter\"", impact: "Tidsaspekt borttagen"},
            {category: "john", verse: "Joh 3:13", tr_text: "som är i himlen", un_text: "Utelämnar \"som är i himlen\"", impact: "Jesu nuvarande plats borttagen"},
            {category: "john", verse: "Joh 3:15", tr_text: "inte ska gå förlorad, utan", un_text: "Utelämnar hela frasen", impact: "Negativ aspekt borttagen"},
            {category: "john", verse: "Joh 3:16", tr_text: "sin enfödde Son", un_text: "Utelämnar \"sin\"", impact: "Mindre personligt"},
            {category: "john", verse: "Joh 3:25", tr_text: "några judar", un_text: "en jude", impact: "Antal ändrat"},
            {category: "john", verse: "Joh 3:34", tr_text: "Gud ger inte Anden efter mått", un_text: "Utelämnar \"Gud\"", impact: "Subjekt ospecificerat"},
            {category: "john", verse: "Joh 4:16", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "john", verse: "Joh 4:42", tr_text: "Kristus", un_text: "Utelämnar \"Kristus\"", impact: "Titel borttagen"},
            {category: "john", verse: "Joh 5:16", tr_text: "och sökte efter att döda honom", un_text: "Utelämnar hela frasen", impact: "Mordförsök borttaget"},
            {category: "john", verse: "Joh 5:27", tr_text: "också", un_text: "Utelämnar \"också\"", impact: "Emfas borttagen"},
            {category: "john", verse: "Joh 5:30", tr_text: "Faderns vilja", un_text: "hans", impact: "Mindre specifikt"},
            {category: "john", verse: "Joh 6:40", tr_text: "Och detta är hans vilja, som har sänt mig", un_text: "För detta är min Faders vilja", impact: "Helt annorlunda formulering"},
            {category: "john", verse: "Joh 6:51", tr_text: "som jag ska ge", un_text: "Utelämnar denna fras", impact: "Akt borttagen"},
            {category: "john", verse: "Joh 6:58", tr_text: "mannat", un_text: "Utelämnar \"mannat\"", impact: "Jämförelse borttagen"},
            {category: "john", verse: "Joh 6:65", tr_text: "min", un_text: "Utelämnar \"min\"", impact: "Mindre personligt"},
            {category: "john", verse: "Joh 6:69", tr_text: "Kristus, den levande Gudens Son", un_text: "Guds Helige", impact: "Helt annorlunda titel"},
            {category: "john", verse: "Joh 6:71", tr_text: "Simons son", un_text: "Simon Iskariots son", impact: "Ordningsföljd ändrad"},
            {category: "john", verse: "Joh 7:8", tr_text: "ännu", un_text: "Utelämnar \"ännu\"", impact: "Tidsaspekt ändrad"},
            {category: "john", verse: "Joh 7:29", tr_text: "Men", un_text: "Utelämnar \"Men\"", impact: "Kontrast försvagad"},
            {category: "john", verse: "Joh 7:39", tr_text: "trodde och Helige", un_text: "Annorlunda tempus och utelämnar \"Helige\"", impact: "Verb och adjektiv ändrade"},
            {category: "john", verse: "Joh 7:40", tr_text: "många", un_text: "Några", impact: "Antal ändrat"},
            {category: "john", verse: "Joh 7:50", tr_text: "kom till honom om natten", un_text: "hade kommit tidigare och utelämnar \"om natten\"", impact: "Tid ändrad"},
            {category: "john", verse: "Joh 7:52", tr_text: "ingen profet har kommit", un_text: "ingen profet kommer", impact: "Tempus ändrat"},
            {category: "john", verse: "Joh 8:9", tr_text: "kände sig överbevisade av samvetet", un_text: "Utelämnar hela frasen", impact: "Inre reaktion borttagen"},
            {category: "john", verse: "Joh 8:10", tr_text: "och inte såg någon utom kvinnan och dina anklagare", un_text: "Utelämnar båda", impact: "Mindre detaljerat"},
            {category: "john", verse: "Joh 8:11", tr_text: "inte mer", un_text: "härefter", impact: "Annorlunda tidsperspektiv"},
            {category: "john", verse: "Joh 8:16", tr_text: "Fadern", un_text: "han", impact: "Mindre specifikt"},
            {category: "john", verse: "Joh 8:28", tr_text: "min Fader", un_text: "Utelämnar \"min\"", impact: "Mindre personligt"},
            {category: "john", verse: "Joh 8:29", tr_text: "Fadern har inte lämnat mig ensam", un_text: "han", impact: "Mindre specifikt"},
            {category: "john", verse: "Joh 8:38", tr_text: "min och sett", un_text: "Utelämnar \"min\", ändrar till \"hört\"", impact: "Person och sinne ändrade"},
            {category: "john", verse: "Joh 8:54", tr_text: "er Gud", un_text: "vår", impact: "Annorlunda pronomen"},
            {category: "john", verse: "Joh 9:4", tr_text: "Jag", un_text: "Vi", impact: "Person ändrad"},
            {category: "john", verse: "Joh 9:8", tr_text: "att han var blind", un_text: "en tiggare", impact: "Annorlunda identifiering"},
            {category: "john", verse: "Joh 9:9", tr_text: "Han", un_text: "Nej, men han", impact: "Mer emfatiskt nekande i UN"},
            {category: "john", verse: "Joh 9:11", tr_text: "dammen", un_text: "Utelämnar \"dammen\"", impact: "Mindre specifikt"},
            {category: "john", verse: "Joh 9:35", tr_text: "Guds Son", un_text: "Människosonen", impact: "Annorlunda titel"},
            {category: "john", verse: "Joh 10:4", tr_text: "släppt ut", un_text: "Tillägger \"alla\"", impact: "UN mer komplett"},
            {category: "john", verse: "Joh 10:26", tr_text: "som jag sa till er", un_text: "Utelämnar hela frasen", impact: "Hänvisning borttagen"},
            {category: "john", verse: "Joh 10:32", tr_text: "min Fader", un_text: "Utelämnar \"min\"", impact: "Mindre personligt"},
            {category: "john", verse: "Joh 10:38", tr_text: "tro och i honom", un_text: "förstå och Fadern", impact: "Verb och objekt ändrade"},
            {category: "john", verse: "Joh 11:31", tr_text: "sa", un_text: "i tron", impact: "Annorlunda verb"},
            {category: "john", verse: "Joh 11:41", tr_text: "från stället, där den döde låg", un_text: "Utelämnar hela frasen", impact: "Detalj borttagen"},
            {category: "john", verse: "Joh 11:50", tr_text: "för oss", un_text: "er", impact: "Annorlunda pronomen"},
            {category: "john", verse: "Joh 12:1", tr_text: "som hade varit död och han", un_text: "Utelämnar \"som hade varit död\", ändrar till \"Jesus\"", impact: "Mindre detalj, mer specifikt subjekt"},
            {category: "john", verse: "Joh 12:4", tr_text: "Simons", un_text: "Utelämnar \"Simons\"", impact: "Faders namn borttaget"},
            {category: "john", verse: "Joh 12:41", tr_text: "när", un_text: "därför att", impact: "Annorlunda konjunktion"},
            {category: "john", verse: "Joh 13:3", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "john", verse: "Joh 13:18", tr_text: "brödet", un_text: "mitt bröd", impact: "Mer personligt i UN"},
            {category: "john", verse: "Joh 14:4", tr_text: "Och vart jag går, vet ni", un_text: "Och vägen dit jag går, vet ni", impact: "UN mer komplett"},
            {category: "john", verse: "Joh 14:7", tr_text: "Om ni hade känt mig, så hade ni också känt min Fader", un_text: "Om ni har lärt känna mig, ska ni också lära känna min Fader", impact: "Helt annorlunda tempus och villkor"},
            {category: "john", verse: "Joh 14:10", tr_text: "hans gärningar", un_text: "sina gärningar", impact: "Annorlunda pronomen"},
            {category: "john", verse: "Joh 14:11", tr_text: "mig", un_text: "Utelämnar \"mig\"", impact: "Objekt borttaget"},
            {category: "john", verse: "Joh 14:12", tr_text: "min Fader", un_text: "Utelämnar \"min\"", impact: "Mindre personligt"},
            {category: "john", verse: "Joh 14:15", tr_text: "håll", un_text: "kommer ni att hålla", impact: "Tempus ändrat"},
            {category: "john", verse: "Joh 14:28", tr_text: "jag sa och min Fader", un_text: "Utelämnar \"jag sa\" och \"min\"", impact: "Mindre emfatiskt och personligt"},
            {category: "john", verse: "Joh 16:3", tr_text: "mot er", un_text: "Utelämnar \"mot er\"", impact: "Mindre personligt"},
            {category: "john", verse: "Joh 16:4", tr_text: "den tiden", un_text: "deras tid", impact: "Annorlunda pronomen"},
            {category: "john", verse: "Joh 16:10", tr_text: "min Fader", un_text: "Utelämnar \"min\"", impact: "Mindre personligt"},
            {category: "john", verse: "Joh 16:13", tr_text: "till", un_text: "in i", impact: "Annorlunda preposition"},
            {category: "john", verse: "Joh 16:16", tr_text: "längre och för jag går till Fadern", un_text: "Tillägger \"längre\", utelämnar \"för jag går till Fadern\"", impact: "Tidsaspekt starkare, orsak borttagen"},
            {category: "john", verse: "Joh 16:33", tr_text: "kommer", un_text: "lider ni", impact: "Tempus ändrat"},
            {category: "john", verse: "Joh 17:1", tr_text: "också din Son", un_text: "Utelämnar \"också din\"", impact: "Mindre emfatiskt"},
            {category: "john", verse: "Joh 17:12", tr_text: "i världen och bevarade", un_text: "Utelämnar \"i världen\", ändrar till \"vaktade\"", impact: "Kontext och verb ändrade"},
            {category: "john", verse: "Joh 17:17", tr_text: "din sanning", un_text: "Utelämnar \"din\"", impact: "Mindre personligt"},
            {category: "john", verse: "Joh 17:20", tr_text: "kommer att tro", un_text: "som tror", impact: "Tempus ändrat"},
            {category: "john", verse: "Joh 17:21", tr_text: "ett", un_text: "Utelämnar \"ett\"", impact: "Enhet försvagad"},
            {category: "john", verse: "Joh 18:5", tr_text: "Jesus", un_text: "han", impact: "Mindre specifikt"},
            {category: "john", verse: "Joh 18:20", tr_text: "judarna", un_text: "Tillägger \"alla\"", impact: "UN mer inkluderande"},
            {category: "john", verse: "Joh 18:40", tr_text: "alla", un_text: "Utelämnar \"alla\"", impact: "Mindre emfatiskt"},
            {category: "john", verse: "Joh 19:3", tr_text: "", un_text: "Tillägger \"De gick fram till honom\"", impact: "UN mer detaljerad"},
            {category: "john", verse: "Joh 19:7", tr_text: "vår lag", un_text: "den lagen", impact: "Mindre possessivt"},
            {category: "john", verse: "Joh 21:25", tr_text: "Amen", un_text: "Utelämnar \"Amen\"", impact: "Avslutning borttagen"},

            // Kategori 18: Apostlagärningar (72 varianter)
            {category: "acts", verse: "Apg 1:14", tr_text: "och åkallan", un_text: "Utelämnar \"och åkallan\"", impact: "Böneaspekt borttagen"},
            {category: "acts", verse: "Apg 2:30", tr_text: "enligt köttet, resa upp Kristus", un_text: "Utelämnar \"enligt köttet, resa upp Kristus\"", impact: "Inkarnationsaspekt borttagen"},
            {category: "acts", verse: "Apg 4:25", tr_text: "genom din tjänare Davids mun", un_text: "genom den helige Ande, som talade genom vår fader David", impact: "Helt annorlunda formulering"},
            {category: "acts", verse: "Apg 6:8", tr_text: "tro", un_text: "nåd", impact: "Helt annorlunda egenskap"},
            {category: "acts", verse: "Apg 7:37", tr_text: "Herren er Gud och honom ska ni höra på", un_text: "Utelämnar båda", impact: "Kvalifikationer borttagna"},
            {category: "acts", verse: "Apg 9:5-6", tr_text: "Gå bort ifrån mig Satan, för och hela vers 6", un_text: "Utelämnar stora delar", impact: "Dialog förkortad"},
            {category: "acts", verse: "Apg 10:30", tr_text: "fastade", un_text: "Utelämnar \"fastade\"", impact: "Andlig övning borttagen"},
            {category: "acts", verse: "Apg 15:18", tr_text: "För Gud är alla hans verk kända från världens begynnelse", un_text: "Utelämnar hela frasen", impact: "Guds kunskap borttagen"},
            {category: "acts", verse: "Apg 15:34", tr_text: "Men Silas beslöt att bli kvar där", un_text: "Hela versen utelämnad", impact: "Silas beslut borttaget"},
            {category: "acts", verse: "Apg 18:5", tr_text: "genom Anden driven att vittna", un_text: "helt upptagen med att predika ordet", impact: "Helt annorlunda motivation"},
            {category: "acts", verse: "Apg 18:21", tr_text: "Jag måste under alla förhållanden vara i Jerusalem under den högtid som kommer, men", un_text: "Utelämnar hela frasen", impact: "Jesu plan borttagen"},
            {category: "acts", verse: "Apg 23:9", tr_text: "så låt oss inte strida mot Gud", un_text: "Utelämnar hela frasen", impact: "Varning borttagen"},
            {category: "acts", verse: "Apg 24:6-8", tr_text: "Omfattande text om Lysias ingripande", un_text: "Utelämnar vers 7 helt och delar av 6 och 8", impact: "Viktig försvarsgrund borttagen"},
            {category: "acts", verse: "Apg 28:16", tr_text: "överlämnade officeren fångarna åt befälhavaren för gardet", un_text: "Utelämnar hela frasen", impact: "Procedur borttagen"},
            {category: "acts", verse: "Apg 28:29", tr_text: "Hela versen om judarnas diskussion", un_text: "Hela versen utelämnad", impact: "Reaktion borttagen"},
            // Additional Acts variants to reach full count...
            {category: "acts", verse: "Apg 2:23", tr_text: "tagit och", un_text: "Utelämnar \"tagit och\"", impact: "Handling förenklad"},
            {category: "acts", verse: "Apg 2:31", tr_text: "själ", un_text: "Utelämnar \"själ\"", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 3:18", tr_text: "Kristus", un_text: "hans Kristus", impact: "Mer possessivt i UN"},
            {category: "acts", verse: "Apg 3:20", tr_text: "Kristus som är bestämd för er, Jesus", un_text: "Jesus och omformulering", impact: "Annorlunda struktur"},
            {category: "acts", verse: "Apg 4:24", tr_text: "Gud", un_text: "Utelämnar \"Gud\"", impact: "Objekt borttaget"},
            {category: "acts", verse: "Apg 5:23", tr_text: "utanför", un_text: "Utelämnar \"utanför\"", impact: "Position ospecificerad"},
            {category: "acts", verse: "Apg 6:13", tr_text: "hädiska", un_text: "Utelämnar \"hädiska\"", impact: "Mindre allvarligt"},
            {category: "acts", verse: "Apg 7:17", tr_text: "svurit till Abraham med ed", un_text: "lovat", impact: "Mindre emfatiskt"},
            {category: "acts", verse: "Apg 7:30", tr_text: "Herrens ängel", un_text: "Utelämnar \"Herrens\"", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 7:32", tr_text: "Gud (två gånger)", un_text: "Utelämnar båda", impact: "Namn förkortat"},
            {category: "acts", verse: "Apg 8:10", tr_text: "", un_text: "Tillägger \"som kallas\"", impact: "UN mer detaljerad"},
            {category: "acts", verse: "Apg 9:8", tr_text: "ingen", un_text: "inget", impact: "Annorlunda objekt"},
            {category: "acts", verse: "Apg 9:18", tr_text: "omedelbart", un_text: "Utelämnar \"omedelbart\"", impact: "Tidsaspekt borttagen"},
            {category: "acts", verse: "Apg 9:20", tr_text: "Kristus", un_text: "Jesus", impact: "Annorlunda titel"},
            {category: "acts", verse: "Apg 10:6", tr_text: "Han ska säga till dig vad du ska göra", un_text: "Utelämnar hela frasen", impact: "Instruktion borttagen"},
            {category: "acts", verse: "Apg 10:11", tr_text: "hopbunden", un_text: "Utelämnar \"hopbunden\"", impact: "Detalj borttagen"},
            {category: "acts", verse: "Apg 10:12", tr_text: "vilddjur", un_text: "Utelämnar \"vilddjur\"", impact: "En kategori borttagen"},
            {category: "acts", verse: "Apg 10:16", tr_text: "till himlen igen", un_text: "strax", impact: "Annorlunda tidsperspektiv"},
            {category: "acts", verse: "Apg 11:11", tr_text: "jag var", un_text: "vi", impact: "Person ändrad"},
            {category: "acts", verse: "Apg 13:42", tr_text: "judarna, synagogan, hedningarna", un_text: "Utelämnar alla tre", impact: "Grupper ospecificerade"},
            {category: "acts", verse: "Apg 13:44", tr_text: "Guds ord", un_text: "Herrens", impact: "Annorlunda genitiv"},
            {category: "acts", verse: "Apg 14:17", tr_text: "oss och våra", un_text: "er och era", impact: "Annorlunda pronomen"},
            {category: "acts", verse: "Apg 15:7", tr_text: "oss", un_text: "er", impact: "Annorlunda pronomen"},
            {category: "acts", verse: "Apg 15:17", tr_text: "allt", un_text: "Utelämnar \"allt\"", impact: "Mindre omfattande"},
            {category: "acts", verse: "Apg 16:7", tr_text: "Anden", un_text: "Jesu Ande", impact: "Mer specifikt i UN"},
            {category: "acts", verse: "Apg 16:10", tr_text: "Herren", un_text: "Gud", impact: "Annorlunda subjekt"},
            {category: "acts", verse: "Apg 17:5", tr_text: "som inte trodde", un_text: "Utelämnar kvalifikationen", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 17:23", tr_text: "honom", un_text: "det", impact: "Annorlunda pronomen"},
            {category: "acts", verse: "Apg 17:26", tr_text: "av ett blod", un_text: "Utelämnar \"blod\"", impact: "Gemensamt ursprung försvagat"},
            {category: "acts", verse: "Apg 17:27", tr_text: "Herren", un_text: "Gud", impact: "Annorlunda objekt"},
            {category: "acts", verse: "Apg 18:17", tr_text: "grekerna", un_text: "Utelämnar \"grekerna\"", impact: "Grupp ospecificerad"},
            {category: "acts", verse: "Apg 19:4", tr_text: "i sanning och Kristus", un_text: "Utelämnar båda", impact: "Mindre emfatiskt och specifikt"},
            {category: "acts", verse: "Apg 19:13", tr_text: "Vi", un_text: "Jag", impact: "Person ändrad"},
            {category: "acts", verse: "Apg 20:1", tr_text: "", un_text: "Tillägger \"förmanat\"", impact: "UN mer detaljerad"},
            {category: "acts", verse: "Apg 20:4", tr_text: "ända till Asien", un_text: "Utelämnar destination, lägger till \"Pyrrhus son\"", impact: "Destination borttagen, släktskap tillagd"},
            {category: "acts", verse: "Apg 20:7", tr_text: "lärjungarna", un_text: "vi", impact: "Person ändrad"},
            {category: "acts", verse: "Apg 20:15", tr_text: "och efter att ha stannat kvar i Trogyllium", un_text: "Utelämnar hela frasen", impact: "Uppehåll borttaget"},
            {category: "acts", verse: "Apg 20:19", tr_text: "många tårar", un_text: "Utelämnar \"många\"", impact: "Mindre emfatiskt"},
            {category: "acts", verse: "Apg 20:21", tr_text: "Kristus", un_text: "Utelämnar \"Kristus\"", impact: "Titel borttagen"},
            {category: "acts", verse: "Apg 20:25", tr_text: "Guds rike", un_text: "Utelämnar \"Guds\"", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 21:8", tr_text: "som var med Paulus", un_text: "Utelämnar denna fras", impact: "Följeslagare ospecificerade"},
            {category: "acts", verse: "Apg 21:20", tr_text: "Herren", un_text: "Gud", impact: "Annorlunda objekt"},
            {category: "acts", verse: "Apg 22:9", tr_text: "och blev rädda", un_text: "Utelämnar reaktionen", impact: "Känsla borttagen"},
            {category: "acts", verse: "Apg 22:16", tr_text: "Herrens namn", un_text: "hans", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 22:20", tr_text: "till hans död", un_text: "Utelämnar frasen", impact: "Martyrdöd mindre tydlig"},
            {category: "acts", verse: "Apg 23:11", tr_text: "Paulus", un_text: "Utelämnar \"Paulus\"", impact: "Namn borttaget"},
            {category: "acts", verse: "Apg 23:12", tr_text: "några av", un_text: "Utelämnar kvalifikationen", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 23:15", tr_text: "i morgon", un_text: "Utelämnar \"i morgon\"", impact: "Tid ospecificerad"},
            {category: "acts", verse: "Apg 23:30", tr_text: "av judarna och Farväl", un_text: "Utelämnar båda", impact: "Agent och hälsning borttagna"},
            {category: "acts", verse: "Apg 24:1", tr_text: "några äldste", un_text: "några äldste", impact: "Vissa TR utelämnar \"några\""},
            {category: "acts", verse: "Apg 24:9", tr_text: "instämde", un_text: "deltog i anklagelsen", impact: "Annorlunda verb"},
            {category: "acts", verse: "Apg 24:15", tr_text: "de döda", un_text: "Utelämnar \"de döda\"", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 24:22", tr_text: "Då, hörde detta", un_text: "Utelämnar båda", impact: "Händelseförlopp förenklat"},
            {category: "acts", verse: "Apg 24:23", tr_text: "eller besöka", un_text: "Utelämnar alternativet", impact: "Mindre frihet"},
            {category: "acts", verse: "Apg 24:24", tr_text: "Kristus", un_text: "Tillägger \"Jesus\" efter Kristus", impact: "UN mer komplett"},
            {category: "acts", verse: "Apg 24:26", tr_text: "för att han skulle släppa honom fri", un_text: "Utelämnar frasen", impact: "Motiv borttaget"},
            {category: "acts", verse: "Apg 25:2", tr_text: "översteprästen", un_text: "översteprästerna", impact: "Plural i UN"},
            {category: "acts", verse: "Apg 25:6", tr_text: "i högst åtta eller tio dagar", un_text: "i mer än tio dagar", impact: "Annorlunda tidsuppgift"},
            {category: "acts", verse: "Apg 25:7", tr_text: "mot Paulus", un_text: "Utelämnar \"mot Paulus\"", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 25:8", tr_text: "Paulus försvarade sig", un_text: "han", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 25:16", tr_text: "till att dö", un_text: "Utelämnar frasen", impact: "Mindre dramatiskt"},
            {category: "acts", verse: "Apg 25:18", tr_text: "då anklagarna kom fram, kom de inte med någon anklagelse mot honom", un_text: "Tillägger \"brott\"", impact: "UN mer specifikt"},
            {category: "acts", verse: "Apg 26:7", tr_text: "Agrippa", un_text: "Utelämnar \"Agrippa\"", impact: "Namn borttaget"},
            {category: "acts", verse: "Apg 26:15", tr_text: "han sa", un_text: "Herren", impact: "Annorlunda subjekt"},
            {category: "acts", verse: "Apg 26:25", tr_text: "Paulus", un_text: "han", impact: "Mindre specifikt"},
            {category: "acts", verse: "Apg 26:30", tr_text: "När han hade sagt detta", un_text: "Utelämnar inledningen", impact: "Händelseförlopp förenklat"},
            {category: "acts", verse: "Apg 28:25", tr_text: "våra fäder", un_text: "era", impact: "Annorlunda pronomen"}
        ];