// merge_verse_data.cjs
// Reads vers_data_original_400.js + verse_data.js (witnesses),
// merges them, and writes verse_data_400_with_witnesses.js
// Run once: node vers_diff_vite/scripts/merge_verse_data.cjs

'use strict';
const fs   = require('fs');
const path = require('path');

// ── Load original 400-verse file ─────────────────────────────────────────────
// File uses `const allVariants = [...]` (no export, no import)
const raw400 = fs.readFileSync(
  path.join(__dirname, '../../vers_data_original_400.js'), 'utf8'
);
const origVariants = Function(raw400 + '\nreturn allVariants;')();

// ── Load new vite verse_data.js ───────────────────────────────────────────────
// File uses `export const allVariants = [...]`
const rawVite = fs.readFileSync(
  path.join(__dirname, '../src/data/verse_data.js'), 'utf8'
).replace(/\bexport\s+const\s+/, 'const '); // strip 'export' so Function() works

const viteVariants = Function(rawVite + '\nreturn allVariants;')();

// ── Build witness lookup: verse string → witnesses object ─────────────────────
const witnessMap = {};
for (const v of viteVariants) {
  if (v.witnesses && !witnessMap[v.verse]) {
    witnessMap[v.verse] = v.witnesses;
  }
}

// ── Merge ─────────────────────────────────────────────────────────────────────
const merged = origVariants.map(v => {
  const w = witnessMap[v.verse];
  return w ? { ...v, witnesses: w } : { ...v };
});

// ── Serialise each entry compactly (witnesses on one line) ────────────────────
function serWitList(arr) {
  return arr.map(w => `{s:${JSON.stringify(w.s)},t:${JSON.stringify(w.t)}}`).join(',');
}

function serEntry(v) {
  const fields = [
    `category:${JSON.stringify(v.category)}`,
    `verse:${JSON.stringify(v.verse)}`,
    `tr_text:${JSON.stringify(v.tr_text)}`,
    `un_text:${JSON.stringify(v.un_text)}`,
    `impact:${JSON.stringify(v.impact)}`,
  ];
  if (v.witnesses) {
    fields.push(
      `witnesses:{tr:[${serWitList(v.witnesses.tr)}],un:[${serWitList(v.witnesses.un)}]}`
    );
  }
  return `  {${fields.join(', ')}}`;
}

// ── Group entries by category for readable section headers ───────────────────
const HEADERS = {
  critical:    'KATEGORI 1 — KRITISKA DOKTRINÄRA VARIANTER',
  significant: 'KATEGORI 2 — BETYDANDE TEOLOGISKA VARIANTER',
  jesus:       'KATEGORI 3 — JESU NAMN OCH TITLAR',
  god:         'KATEGORI 4 — GUDS NAMN OCH ATTRIBUT',
  spirit:      'KATEGORI 5 — DEN HELIGE ANDE',
  family:      'KATEGORI 6 — JUNGFRUFÖDELSEN OCH FAMILJ',
  miracles:    'KATEGORI 7 — UNDERGÖRELSER',
  ethics:      'KATEGORI 8 — ETIK OCH KRISTET LIV',
  names:       'KATEGORI 9 — GEOGRAFISKA OCH PERSONNAMN',
  church:      'KATEGORI 10 — FÖRSAMLINGSORDNING OCH SAKRAMENT',
  resurrection:'KATEGORI 11 — UPPSTÅNDELSEN OCH EFTERÅT',
  prophecy:    'KATEGORI 12 — PROFETIOR OCH UPPFYLLELSER',
  sin:         'KATEGORI 13 — DOKTRIN OM SYND OCH HELGELSE',
  ministry:    'KATEGORI 14 — KRISTEN KALLELSE OCH TJÄNST',
  eschatology: 'KATEGORI 15 — HIMMELSKA SCENER OCH ESKATOLOGI',
  minor:       'KATEGORI 16 — MINDRE VARIANTER',
  john:        'KATEGORI 17 — JOHANNESEVANGELIET',
  acts:        'KATEGORI 18 — APOSTLAGÄRNINGAR',
};

let lastCat = null;
const lines = [];
for (const v of merged) {
  if (v.category !== lastCat) {
    const hdr = HEADERS[v.category] || v.category.toUpperCase();
    lines.push('');
    lines.push(`// ${'═'.repeat(67)}`);
    lines.push(`// ${hdr}`);
    lines.push(`// ${'═'.repeat(67)}`);
    lastCat = v.category;
  }
  lines.push(serEntry(v) + ',');
}
// Remove trailing comma on last entry
if (lines.length) {
  lines[lines.length - 1] = lines[lines.length - 1].replace(/,$/, '');
}

const withWitnesses = merged.filter(v => v.witnesses).length;

const output = `\
// verse_data_400_with_witnesses.js
// ─────────────────────────────────────────────────────────────────────────────
// SOURCE:  vers_data_original_400.js  (all ${merged.length} verse variants)
// WITNESS: verse_data.js              (${withWitnesses} entries enriched with manuscript data)
// ─────────────────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE — regenerate with:
//   node vers_diff_vite/scripts/merge_verse_data.cjs
//
// Witness type codes:
//   pap = papyrus   cod = major codex   byz = Byzantine/minuscule
//   ver = ancient version   pat = church father   tr = printed TR edition
//
// witnesses.tr = manuscripts supporting the TR/majority reading
// witnesses.un = manuscripts supporting the NA/UBS (omission) reading

export const allVariants = [
${lines.join('\n')}
];
`;

const outPath = path.join(__dirname, '../src/data/verse_data_400_with_witnesses.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log(`✓ Written ${outPath}`);
console.log(`  Total verses : ${merged.length}`);
console.log(`  With witnesses: ${withWitnesses}`);
console.log(`  Without       : ${merged.length - withWitnesses}`);
